services:
  master-node:
    build:
      context: . # directory from which we build
      dockerfile: Dockerfile
      target: master_image
    ports:
      - "60000:60000"
      - "8080:8080"
    tty: true
    environment:
      - LOGGRID_INPUT_DIR=/app/data
      - LOGGRID_OUTPUT_DIR=/data/loggrid
    volumes:
      - /data/logs:/app/data:ro
      - "/data/loggrid:/data/loggrid"

  worker-1:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker_image
    depends_on:
      - master-node
    tty: true # -it option
    volumes:
      - /data/logs:/app/data:ro # read only

  worker-2:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker_image
    depends_on:
      - master-node
    tty: true # -it option
    volumes:
      - /data/logs:/app/data:ro # read only