name: LogGrid CI

# start condition
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker images
      run: docker compose build

    # Run tests
    - name: Run GTest suite
      run: docker compose run --rm master-node /app/build/tests/LogGridTests
