name: LogGrid CI

# start condition
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker images
      run: docker compose build

    # Run tests
    - name: Build test image
      run: docker build --target test_image -t loggrid-tests .

    - name: Run GTest suite
      run: docker run --rm loggrid-tests

  coverage:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build coverage image
      run: docker build --target coverage_image -t loggrid-coverage .

    - name: Run coverage pipeline
      run: |
        docker run --name coverage-run loggrid-coverage
        docker cp coverage-run:/usr/src/app/build/coverage/html ./coverage-html
        docker rm coverage-run

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage-html/
        retention-days: 7